
import { RequirementOption, VibeFormData } from './types';

export const DEFAULT_FORM_DATA: VibeFormData = {
  siteName: '星云',
  brand: 'DMDII.TOP',
  brandLink: 'https://www.dmdii.top',
  hasMembership: true,
  memberFeatures: '',
  passwordRules: 'SN-****,其中*为数字',
  requirements: ['detailed-comments', 'responsive-design', 'no-llm'],
  language: 'zh',
  colorTone: 'dark',
  additionalFeatures: '',
};

export const REQUIREMENT_OPTIONS: RequirementOption[] = [
  { id: 'detailed-comments', label: { zh: '提供详细代码注释', en: 'Provide Detailed Code Comments' }, icon: '📝' },
  { id: 'documentation', label: { zh: '提供项目说明文档', en: 'Provide Project Documentation' }, icon: '📚' },
  { id: 'responsive-design', label: { zh: '支持PC和手机访问', en: 'Support PC and Mobile Access' }, icon: '📱' },
  { id: 'no-llm', label: { zh: '只使用代码功能，不调用任何大模型', en: 'Use Code Features Only, No LLM Calls' }, icon: '🚫' },
];

export const UI_STRINGS = {
  zh: {
    title: 'Vibe Coding',
    subtitle: '提示词',
    desc: '快速输出前端项目提示词（持续优化）',
    configTitle: '架构配置',
    projectName: '项目名称',
    brandName: '品牌 / 组织',
    refLink: '参考链接',
    membership: '会员系统',
    memberFeatures: '会员功能',
    memberFeaturesPlaceholder: '例如：去水印功能',
    enabled: '启用',
    disabled: '禁用',
    securityRules: '安全 / 密码规则',
    ruleNote: '注：规则将集成到最终的编码指令中。',
    additionalFeaturesTitle: '核心功能描述',
    additionalPlaceholder: '在此输入具体的功能描述或业务逻辑...',
    featureConstraints: '架构指令',
    colorTone: '网站色调风格',
    darkTone: '深色系',
    lightTone: '浅色系',
    previewTitle: '提示词预览',
    copyBtn: '复制提示词',
    resetBtn: '重置架构',
    resetConfirm: '确定要重置架构师配置吗？',
    copySuccess: '提示词已复制到剪贴板！',
    resetSuccess: '架构师已成功重置。',
    footerBuilt: '专为 Vibe Coding 打造',
    footerCopyright: '2025 Vibe Coding 提示词',
    docs: '',
    manifesto: '',
  },
  en: {
    title: 'Vibe Coding',
    subtitle: 'Prompt',
    desc: 'Design professional prompt structures for your frontend project.',
    configTitle: 'Architect Configuration',
    projectName: 'Project Name',
    brandName: 'Brand / Organization',
    refLink: 'Primary Reference Link',
    membership: 'Membership System',
    memberFeatures: 'Member Features',
    enabled: 'Enabled',
    disabled: 'Disabled',
    securityRules: 'Security / Password Rules',
    ruleNote: 'Note: Rules will be integrated into the final coding instructions.',
    additionalFeaturesTitle: 'Core Functionality',
    additionalPlaceholder: 'Enter specific feature descriptions or business logic here...',
    featureConstraints: 'Architectural Directives',
    colorTone: 'Color Tone Style',
    darkTone: 'Dark Tone',
    lightTone: 'Light Tone',
    previewTitle: 'Prompt Preview',
    copyBtn: 'Copy Prompt',
    resetBtn: 'Reset',
    resetConfirm: 'Are you sure you want to reset the architect?',
    copySuccess: 'Prompt copied to clipboard!',
    resetSuccess: 'Architect reset successfully.',
    footerBuilt: 'Built for the Vibe Coding community. No LLM integration used for this logic.',
    footerCopyright: '2025 Vibe Coding Prompt',
    docs: '',
    manifesto: '',
  }
};
